// <auto-generated />
namespace QuanLyThongTinDaoTao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _4582222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4582222));
        
        string IMigrationMetadata.Id
        {
            get { return "202503270836515_4582222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
