// <auto-generated />
namespace QuanLyThongTinDaoTao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _405 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_405));
        
        string IMigrationMetadata.Id
        {
            get { return "202504040905547_405"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
