// <auto-generated />
namespace QuanLyThongTinDaoTao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NEWUPDATE428 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NEWUPDATE428));
        
        string IMigrationMetadata.Id
        {
            get { return "202503310928292_NEWUPDATE428"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
