// <auto-generated />
namespace QuanLyThongTinDaoTao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _32132 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_32132));
        
        string IMigrationMetadata.Id
        {
            get { return "202503181759067_32132"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
