// <auto-generated />
namespace QuanLyThongTinDaoTao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _7daddadswbbv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_7daddadswbbv));
        
        string IMigrationMetadata.Id
        {
            get { return "202503170210027_7daddadswbbv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
